#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pm-graph
Version  : 5.1
Release  : 1
URL      : https://github.com/01org/pm-graph/archive/5.1.tar.gz
Source0  : https://github.com/01org/pm-graph/archive/5.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pm-graph-bin
Requires: pm-graph-license
Requires: pm-graph-man
Patch1: 0001-Use-relative-paths-for-symlinks.patch

%description
A n a l y z e S u s p e n d
AnalyzeSuspend: suspend/resume timing analysis tool
Version: 4.4
Author: Todd Brandt <todd.e.brandt@linux.intel.com>
Home Page: https://01.org/suspendresume

%package bin
Summary: bin components for the pm-graph package.
Group: Binaries
Requires: pm-graph-license
Requires: pm-graph-man

%description bin
bin components for the pm-graph package.


%package doc
Summary: doc components for the pm-graph package.
Group: Documentation
Requires: pm-graph-man

%description doc
doc components for the pm-graph package.


%package license
Summary: license components for the pm-graph package.
Group: Default

%description license
license components for the pm-graph package.


%package man
Summary: man components for the pm-graph package.
Group: Default

%description man
man components for the pm-graph package.


%prep
%setup -q -n pm-graph-5.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535749293
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1535749293
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pm-graph
cp COPYING %{buildroot}/usr/share/doc/pm-graph/COPYING
cp debian/copyright %{buildroot}/usr/share/doc/pm-graph/debian_copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/pm-graph/bootgraph.py
/usr/lib/pm-graph/config/cgskip.txt
/usr/lib/pm-graph/config/freeze-callgraph.cfg
/usr/lib/pm-graph/config/freeze-dev.cfg
/usr/lib/pm-graph/config/freeze.cfg
/usr/lib/pm-graph/config/standby-callgraph.cfg
/usr/lib/pm-graph/config/standby-dev.cfg
/usr/lib/pm-graph/config/standby.cfg
/usr/lib/pm-graph/config/suspend-callgraph.cfg
/usr/lib/pm-graph/config/suspend-dev.cfg
/usr/lib/pm-graph/config/suspend-x2-proc.cfg
/usr/lib/pm-graph/config/suspend.cfg
/usr/lib/pm-graph/sleepgraph.py

%files bin
%defattr(-,root,root,-)
/usr/bin/bootgraph
/usr/bin/sleepgraph

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/pm\-graph/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/pm-graph/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/bootgraph.8
/usr/share/man/man8/sleepgraph.8
