#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v3
# autospec commit: c1050fe
#
Name     : pm-graph
Version  : 5.11
Release  : 13
URL      : https://github.com/intel/pm-graph/archive/5.11/pm-graph-5.11.tar.gz
Source0  : https://github.com/intel/pm-graph/archive/5.11/pm-graph-5.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pm-graph-bin = %{version}-%{release}
Requires: pm-graph-license = %{version}-%{release}
Requires: pm-graph-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
_
_ __  _ __ ___         __ _ _ __ __ _ _ __ | |__
| '_ \| '_ ` _ \ _____ / _` | '__/ _` | '_ \| '_ \
| |_) | | | | | |_____| (_| | | | (_| | |_) | | | |
| .__/|_| |_| |_|      \__, |_|  \__,_| .__/|_| |_|
|_|                    |___/          |_|

%package bin
Summary: bin components for the pm-graph package.
Group: Binaries
Requires: pm-graph-license = %{version}-%{release}

%description bin
bin components for the pm-graph package.


%package license
Summary: license components for the pm-graph package.
Group: Default

%description license
license components for the pm-graph package.


%package man
Summary: man components for the pm-graph package.
Group: Default

%description man
man components for the pm-graph package.


%prep
%setup -q -n pm-graph-5.11
cd %{_builddir}/pm-graph-5.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702060071
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702060071
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pm-graph
cp %{_builddir}/pm-graph-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pm-graph/a7a897a4bde987e597c04f16a9c28f6d3f57916d || :
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/pm-graph/argconfig.py
/usr/lib/pm-graph/bootgraph.py
/usr/lib/pm-graph/config/cgskip.txt
/usr/lib/pm-graph/config/freeze-callgraph.cfg
/usr/lib/pm-graph/config/freeze-dev.cfg
/usr/lib/pm-graph/config/freeze.cfg
/usr/lib/pm-graph/config/standby-callgraph.cfg
/usr/lib/pm-graph/config/standby-dev.cfg
/usr/lib/pm-graph/config/standby.cfg
/usr/lib/pm-graph/config/suspend-callgraph.cfg
/usr/lib/pm-graph/config/suspend-dev.cfg
/usr/lib/pm-graph/config/suspend-x2-proc.cfg
/usr/lib/pm-graph/config/suspend.cfg
/usr/lib/pm-graph/netfix.py
/usr/lib/pm-graph/sleepgraph.py

%files bin
%defattr(-,root,root,-)
/usr/bin/bootgraph
/usr/bin/netfix
/usr/bin/sleepgraph

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pm-graph/a7a897a4bde987e597c04f16a9c28f6d3f57916d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bootgraph.8
/usr/share/man/man8/sleepgraph.8
